name: Deploy Python App

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: |
        ssh -T root@212.86.108.148 || RiRZ67NypnZL | git clone https://github.com/Hijacker555/telebot.git


